CREATE DATABASE IF NOT EXISTS tickets_db2_0;
USE tickets_db2_0;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);
